### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by kwucheuwkzbAks** [LondonX/clash_flt#1]
lib/plugin_functions_view.dart:9:8: Error: Error when reading 'lib/sensitive_info.dart': No such file or directory
    import 'sensitive_info.dart';
           ^
    lib/plugin_functions_view.dart:67:19: Error: The getter 'clashProfileUrl' isn't defined for the class '_PluginFunctionsViewState'.
     - '_PluginFunctionsViewState' is from 'package:clash_flt_example/plugin_functions_view.dart' ('lib/plugin_functions_view.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'clashProfileUrl'.
                      clashProfileUrl,
                      ^^^^^^^^^^^^^^^

**Comment by LondonX** [comment]
Thanks for submitting issue.
But you may have to fill your own `yaml` url.
Just like the filename `sensitive_info` means it contains the `clashProfileUrl` that I cannot tell you. 😊
