### ISSUE TITLE
Android stopClash fail

### ISSUE THREAD

**Issue by DizzyDuan** [LondonX/clash_flt#11]
await ClashFlt.instance.stopClash();

question:
When the application is running, if you turn off the VPN and turn it on again, the VPN will become invalid. Now start the VPN during cold boot to take effect.

The system's VPN is not closed after calling stopClash.

**Comment by LondonX** [comment]
Any more info? Android or iOS, OS version, logs?

**Comment by DizzyDuan** [comment]
Android stopClash does not stop after

**Comment by LondonX** [comment]
No further information provided, closing this issue.
