### ISSUE TITLE
我希望能有偿提供一些合理的需求 否则这个项目的进度太慢了 

### ISSUE THREAD

**Issue by dollar-cat** [LondonX/clash_flt#12]
我想替换成clash mate core

**Comment by dollar-cat** [comment]
如果可以请留下 联系方式 我会联系你 更新太慢了

**Comment by LondonX** [comment]
1. 暂时没有能力承接任何有偿开发工作。
2. 不是很了解Clash Mate，目前的Clash内核是基于ClashKit使用gomobile编译的，这个改动可能会非常大。
3. 更换内核是想在更多的平台Windows/Mac上用？

**Comment by dollar-cat** [comment]
clash mate 在协议上的支持更多 比clash更稳定 我只希望能通过有偿 给你提供动力 让这个项目变得更好

**Comment by dollar-cat** [comment]
目前这个项目进度太慢了 使用的clash较旧

**Comment by LondonX** [comment]
如果你有兴趣可以加入我的另一个private repo，已经发送邀请给你，基于https://github.com/Fclash/Fclash开发的clash_flt2，因为Fclash有meta的分支，这个事情应该会容易很多。clash_flt2最终也是要开源出来的，额外支持Windows和Mac，而且各平台的native lib也完全统一。

**Comment by shangjiyu** [comment]
clash meta 导出的 xcframework 我 build undefined symbol。。。 link command failed ... 何解 @dollar-cat

**Comment by shangjiyu** [comment]
> @shangjiyu 会不会是clash删库跑路导致的？可以试试在go.mod里replace掉一些clash相关的依赖试试，如果github上有人备份了的话，1.18.0版本理论上都能用。

clash 1.18.0 我也没问题，clash  meta 分支导出的clashkit 有问题，，🤣 @LondonX

**Comment by jzau** [comment]
@LondonX 想问下 clash_flt2 还有在开发嘛？能否邀请下，我有时间和兴趣加入一起开发，感谢🙏

**Comment by LondonX** [comment]
[clash_flt2](https://github.com/LondonX/clash_flt2)现已开源，欢迎PR
