### ISSUE TITLE
全局模式

### ISSUE THREAD

**Issue by dollar-cat** [LondonX/clash_flt#14]
什么时候才能支持全局模式 很难受呀 老哥 改配置文件使其全局 目前似乎不可行 问题还多 哭了 催更好久了我

**Comment by LondonX** [comment]
近期比较忙，过两周把clash_flt2完善一下就开源，那个用的core也更新，理论上能满足你的一切想法。

**Comment by dollar-cat** [comment]
你好像没有发链接我 我没看到你的clash_flt2仓库

**Comment by LondonX** [comment]
重新发了一下邀请
https://github.com/LondonX/clash_flt2/invitations

**Comment by dollar-cat** [comment]
非常感谢您无私的开源精神

**Comment by LondonX** [comment]
[clash_flt2](https://github.com/LondonX/clash_flt2)现已开源，欢迎PR
