### ISSUE TITLE
vpn失效

### ISSUE THREAD

**Issue by dollar-cat** [LondonX/clash_flt#15]
#11 
我也出现了 flt2也有这个问题 突然失效 我删了重装 各种启动也无效 我检查过我的订阅服务节点 它正常工作 
<img width="1288" alt="截屏2023-10-27 15 18 12" src="https://github.com/LondonX/clash_flt/assets/72382917/c65972e1-feb1-445b-b38c-44c577830a69">
<img width="1322" alt="截屏2023-10-27 15 18 21" src="https://github.com/LondonX/clash_flt/assets/72382917/88e2605a-f73c-459f-9f37-1b47de95e396">
<img width="1426" alt="截屏2023-10-27 15 18 57" src="https://github.com/LondonX/clash_flt/assets/72382917/9eb87e8b-d9b4-43fd-8347-1124ab644603">
运行设备安卓

**Comment by dollar-cat** [comment]
首次使用新节点订阅 它是正常工作的 当我stopClash 再startClash 它整个失效了 我尝试使用一个未使用过新订阅地址 它又正常工作 如果我stopClash  再startClash  它又失效

**Comment by dollar-cat** [comment]
flt2 也会有这个问题 我没有办法完全复现出现 经常容易失效 失效 我怎么操作 都没有反应 有时候突然就可以了 但stopClash 马上失效 浏览器显示'连接被该站点关闭' 我检查过我的节点状态 它正常
<img width="1277" alt="截屏2023-10-27 15 41 00" src="https://github.com/LondonX/clash_flt/assets/72382917/7d3df0e6-d1b4-4c41-8559-fd6aab1a4a29">

**Comment by dollar-cat** [comment]
不可思议 我在另一部安卓设备上stopClash 再startClash 是正常的

**Comment by dollar-cat** [comment]
我多次测试 部分机型在stopClash 后再startClash vpn失效  重新启动 安装也无效 关闭软件后大约过一段时间会正常  部分机型没有这个问题

**Comment by dollar-cat** [comment]
失效设备 安卓 oppo a8 android版本9

**Comment by dollar-cat** [comment]
失效设备使用 [ClashForAndroid](https://github.com/Kr328/ClashForAndroid)可以正常使用 另一台没有失效的设备androidt版本是12

**Comment by LondonX** [comment]
看看是不是Tun2Socks的问题

**Comment by dollar-cat** [comment]
我对tun2socks不懂 我不会排查 它也没有什么异常报错 我该怎么去做 ft2也会这样

**Comment by dollar-cat** [comment]
我会尝试联系Tun2Socks作者 麻烦老哥有空有看看这个问题

**Comment by dollar-cat** [comment]
tun2socks 作者说那个项目太旧了 没有足够的时间维护 老哥有没有考虑 放弃这个项目 专注flt2 并替换较新的tun2socks库

**Comment by dollar-cat** [comment]
呜呜呜呜 好高冷的老哥 已读不回

**Comment by LondonX** [comment]
#18 Duplicated
