### ISSUE TITLE
HevSocks5Tunnel.xcframework删库了，请问有备份吗？

### ISSUE THREAD

**Issue by shoumo680** [LondonX/clash_flt#19]
failed downloading 'https://github.com/arror/Tun2SocksKit/releases/download/2.5.3/HevSocks5Tunnel.xcframework.zip' which is required by binary target 'HevSocks5Tunnel': badResponseStatusCode(404)

**Comment by shoumo680** [comment]
找到了

**Comment by LondonX** [comment]
你这么一说我也才发现跑路了，我也fork了这个https://github.com/onlypl/Tun2SocksKit ，只是fork了还没编译测试。

**Comment by shoumo680** [comment]
https://github.com/whatbugsyou/hev-socks5-tunnel，这里有编译好的。
