### ISSUE TITLE
iOS can't connect to the internet when start clash

### ISSUE THREAD

**Issue by Devoperman** [LondonX/clash_flt#21]
Hi, by using default configuration on iOS, the app can't connect to the internet. (flutter dio http)
What should I do? Thanks.

**Comment by laikee99** [comment]
Act as timeout

**Comment by Devoperman** [comment]
It won't work after ruuning for few minutes, like can not connect to the network

**Comment by LondonX** [comment]
Hi, you may try this package https://pub.dev/packages/http_proxy to see if works on your case

run the code after VPN services is started:
```dart
  final httpProxy = await HttpProxy.createHttpProxy();
  HttpOverrides.global = httpProxy;
```

**Comment by Devoperman** [comment]
> Hi, you may try this package https://pub.dev/packages/http_proxy to see if works on your case
> 
> run the code after VPN services is started:
> 
> ```dart
>   final httpProxy = await HttpProxy.createHttpProxy();
>   HttpOverrides.global = httpProxy;
> ```

Thanks, I think it's working now :)
