### ISSUE TITLE
badvpn tun2socks can't proxy the traffic after calling stopClash

### ISSUE THREAD

**Issue by Devoperman** [LondonX/clash_flt#22]
Hi, I'm trying to use `stopClash` then `startClash`, and I found that some APP such like telegram can't connect to the network.
But if it was the first time call `startClash` the APP could work. 
Could you please provide me some ideas?
The version is the latest, and the platform is Android 13.
Thank you so much!

**Comment by Devoperman** [comment]
NOTICE(tun2socks): tearing down
NOTICE(tun2socks): exiting
I/native-lib(12328): NOTICE(tun2socks): initializing BadVPN tun2socks 1.999.130
I/native-lib(12328): NOTICE(tun2socks): entering event loop
I/native-lib(12328): INFO(tun2socks): UDP: from device 32 bytes
I/native-lib(12328): INFO(tun2socks): UDP: from SOCKS UDP 109 bytes

Becuase I set UDP to be true, so it will handle the UDP traffic but no TCP socks up.

**Comment by LondonX** [comment]
Did you call `startClash` immediately after `stopClash`?
try `await stopClash()` before start.
