### ISSUE TITLE
clash规则 和 全局模式

### ISSUE THREAD

**Issue by dollar-cat** [LondonX/clash_flt#3]
clash有规则 和 全局模式 但是我没找到 有调用这些模式的api 希望能添加上去 如果已经添加了 麻烦可以指点一下

**Comment by LondonX** [comment]
感谢你的反馈
目前的方法是重载配置文件中的`rules`，设置为`MATCH,Proxy`即全局模式。
可以尝试使用[yaml_edit](https://pub.dev/packages/yaml_edit)来实现yaml的编辑。

虽然不够优雅，但确实可行😂

**Comment by wisdomTechnologyIoT** [comment]
全局模式如何去实现调用

**Comment by LondonX** [comment]
> 感谢你的反馈 目前的方法是重载配置文件中的`rules`，设置为`MATCH,Proxy`即全局模式。 可以尝试使用[yaml_edit](https://pub.dev/packages/yaml_edit)来实现yaml的编辑。
> 
> 虽然不够优雅，但确实可行😂
