### ISSUE TITLE
开启VPN无法上网

### ISSUE THREAD

**Issue by dollar-cat** [LondonX/clash_flt#4]
老哥 启用VPN后无法上网 我检查多次 并替换过代理商 手机 发现并不是我的问题  我很奇怪 为什么所有的服务都无网络连接

**Comment by dollar-cat** [comment]
我使用的是新版clash配置 _$ProfileFromJson 解析配置方法里是socksPort: json['socks-port'] as int, 新版配置使用的是 是mixedPort 而不是 socksPort 我将代码里socksPort 改为 mixedPort  不知道是不是这个问题导致的

**Comment by dollar-cat** [comment]
我没有旧版配置去尝试 现在使用的都是新版clash配置

**Comment by LondonX** [comment]
可能是mixedPort的问题，可以尝试把mixedPort拆成socksPort和port两个属性试试

**Comment by dollar-cat** [comment]
使用的是旧版core嘛

**Comment by dollar-cat** [comment]
我找到了到具体问题 是安卓设置vpn给prot值时读取了clash配置文件里的socksPort设置 而我只改了dart里的socksPort
